# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Petometer2' do
	pod 'Gifu'
end

target 'Petometer2Tests' do

end

target 'Petometer2UITests' do

end

